export const homeObject = {
  español: {
    header: {
      title: 'Rocha',
      subTitle: 'Relojes suizos exclusivos',
      navBar: [
        { title: 'inicio', path: '/' },
        { title: 'tienda', path: '/store' },
        { title: 'nosotros', path: '/about' },
        { title: 'Preguntas', path: '/questions' },
        { title: 'contacto', path: '/contact' },
      ],
    },
    homeContent: {
      publicity: {
        title: 'Lorem ipsum dolor sit amet.',
        content:
          'Lorem ipsum dolor sit amet consectetur adipisicing elit. Enim, fuga architecto? Accusantium porro exercitationem nisi nobis, totam voluptate animi ipsa minima rerum unde nemo fugit voluptatum harum praesentium natus iure?',
      },
      carruselImg: [
        {
          id: 1,
          src: './assets/img/prin_05.jfif',
        },
        {
          id: 2,
          src: './assets/img/prin_02.jfif',
        },
        {
          id: 3,
          src: './assets/img/prin_03.jpg',
        },
        {
          id: 4,
          src: './assets/img/prin_04.jfif',
        },
      ],
      product: [
        {
          id: 1,
          src: './assets/img/reloj_01.webp',
          isOfert: true,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 2,
          src: './assets/img/reloj_02.jpg',
          isOfert: true,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 3,
          src: './assets/img/reloj_03.jpg',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 4,
          src: './assets/img/reloj_04.jpg',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 5,
          src: './assets/img/reloj_05.jpg',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 6,
          src: './assets/img/reloj_06.jpg',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 7,
          src: './assets/img/reloj_07.jfif',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 8,
          src: './assets/img/reloj_08.jfif',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 9,
          src: './assets/img/reloj_09.jfif',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
        {
          id: 10,
          src: './assets/img/reloj_10.jpg',
          isOfert: false,
          title: 'producto',
          price: 19.99,
          clickTitle: 'click para ver',
          maxCant: 10,
        },
      ],
      titleOfert: 'En oferta',
      isSelected: {
        id: 1,
        isOfert: false,
        title: '',
        price: 0,
        maxCant: 0,
      },
    },
    footer: { title: '©2021 por ROCHA. Creado por GRIALS.' },
  },
  english: {
    header: {
      title: '',
      subTitle: '',
      navBar: [
        { title: 'inicio', path: '/' },
        { title: 'tienda', path: '/store' },
        { title: 'nosotros', path: '/about' },
        { title: 'Preguntas', path: '/questions' },
        { title: 'contacto', path: '/contact' },
      ],
    },
  },
};
