export const storeShopObject = {
  español: {
    titleOfert: 'En oferta',
    products: [
      {
        id: 1,
        src: './assets/img/reloj_01.webp',
        isOfert: true,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 2,
        src: './assets/img/reloj_02.jpg',
        isOfert: true,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 3,
        src: './assets/img/reloj_03.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 4,
        src: './assets/img/reloj_04.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 5,
        src: './assets/img/reloj_05.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 6,
        src: './assets/img/reloj_06.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 7,
        src: './assets/img/reloj_07.jfif',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 8,
        src: './assets/img/reloj_08.jfif',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 9,
        src: './assets/img/reloj_09.jfif',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 10,
        src: './assets/img/reloj_10.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
    ],
  },
  english: {
    titleOfert: 'En oferta',
    products: [
      {
        id: 1,
        src: './assets/img/reloj_01.webp',
        isOfert: true,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 2,
        src: './assets/img/reloj_02.jpg',
        isOfert: true,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 3,
        src: './assets/img/reloj_03.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 4,
        src: './assets/img/reloj_04.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 5,
        src: './assets/img/reloj_05.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 6,
        src: './assets/img/reloj_06.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 7,
        src: './assets/img/reloj_07.jfif',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 8,
        src: './assets/img/reloj_08.jfif',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 9,
        src: './assets/img/reloj_09.jfif',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
      {
        id: 10,
        src: './assets/img/reloj_10.jpg',
        isOfert: false,
        title: 'producto',
        price: 19.99,
        clickTitle: 'click para ver',
        maxCant: 10,
      },
    ],
  },
};
